The Iris flower dataset consists of three species: setosa, versicolor,
and virginica. These species can be distinguished based on their
measurements. Now, imagine that you have the measurements
of Iris flowers categorized by their respective species. Your
objective is to train a machine learning model that can learn from
these measurements and accurately classify the Iris flowers into
their respective species.
Use the Iris dataset to develop a model that can classify iris
flowers into different species based on their sepal and petal
measurements. This dataset is widely used for introductory
classification tasks.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## Importing important libraries first

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
# Import the dataset using Seaborn library
iris=pd.read_csv('/content/IRIS.csv')

In [5]:
# Checking the dataset
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# Creating a pairplot to visualize the similarities and especially difference between the species
sns.pairplot(data=iris, hue='species', palette='Set2')

## Train Test Split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
# Separating the independent variables from dependent variables
x=iris.iloc[:,:-1]
y=iris.iloc[:,4]
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30)

## Training and Fitting the model

In [9]:
from sklearn.svm import SVC
model=SVC()

In [10]:
model.fit(x_train, y_train)

SVC()

## Predictions from the trained model

In [11]:
pred=model.predict(x_test)

## Model Evaluation

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [17]:
print(confusion_matrix(y_test,pred))

[[11  0  0]
 [ 0 17  1]
 [ 0  0 16]]


In [18]:
print(classification_report(y_test, pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.94      0.97        18
 Iris-virginica       0.94      1.00      0.97        16

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

